---
- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    # Переменные для тестового окружения
    domain_name: "matrix.test"
    admin_email: "admin@test.com"
    # Флаг что мы в тестовом окружении
    molecule_test: true
    
  tasks:
    - name: Test - just verify we can connect and gather facts
      debug:
        msg: "Successfully connected to {{ inventory_hostname }} running {{ ansible_distribution }} {{ ansible_distribution_version }}"
        
    - name: Test - check we can run commands
      command: whoami
      register: whoami_result
      changed_when: false
      
    - name: Display current user
      debug:
        msg: "Current user: {{ whoami_result.stdout }}"