---
- name: Converge
  hosts: all
  become: yes
  vars:
    # Переменные для тестового окружения
    domain_name: "{{ lookup('env', 'DOMAIN_NAME') | default('matrix.test') }}"
    admin_email: "{{ lookup('env', 'ADMIN_EMAIL') | default('admin@test.com') }}"
    # Флаг что мы в тестовом окружении
    molecule_test: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Install systemd for Docker container
      apt:
        name:
          - systemd
          - systemd-sysv
        state: present
        
  tasks:
    # Выполняем только базовые задачи для проверки синтаксиса
    - name: Include install_synapse tasks
      include_tasks: ../../tasks/install_synapse.yml
      
    - name: Include setup_postgres tasks
      include_tasks: ../../tasks/setup_postgres.yml
      
    - name: Include integrate_postgres_with_synapse tasks
      include_tasks: ../../tasks/integrate_postgres_with_synapse.yml
      
    # Пропускаем SSL и nginx в тестах - они требуют реальный домен
    # - name: Include setup_nginx tasks
    #   include_tasks: ../../tasks/setup_nginx.yml
    
    # - name: Include setup_ssl tasks  
    #   include_tasks: ../../tasks/setup_ssl.yml
    
    - name: Include setup_security tasks
      include_tasks: ../../tasks/setup_security.yml
      
    - name: Include setup_monitoring tasks
      include_tasks: ../../tasks/setup_monitoring.yml
      
    - name: Include backup tasks
      include_tasks: ../../tasks/backup.yml