---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    # Переменные для тестового окружения
    domain_name: "matrix.test"
    admin_email: "admin@test.com"
    # Флаг что мы в тестовом окружении
    molecule_test: true
    
  pre_tasks:
    - name: Wait for systemd to be ready
      wait_for:
        path: /run/systemd/system
        state: present
        timeout: 30
      ignore_errors: yes
        
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_update
      retries: 3
      delay: 5
      until: apt_update is success
      
  tasks:
    - name: Test - just verify we can connect
      debug:
        msg: "Successfully connected to {{ inventory_hostname }}"