dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: matrix-test
    image: ubuntu:22.04
    pre_build_image: true
    command: >
      bash -c "apt-get update && 
      apt-get install -y python3 python3-apt sudo bash ca-certificates &&
      tail -f /dev/null"
    privileged: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - matrix_servers
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      host_key_checking: false
      callback_whitelist: profile_tasks
  env:
    ANSIBLE_HOST: "localhost"
    ANSIBLE_USER: "root"
    ANSIBLE_PASSWORD: "test_password"
    MATRIX_ADMIN_PASSWORD: "test_admin_pass"
    MATRIX_ADMIN_USERNAME: "admin"
    POSTGRES_PASSWORD: "test_db_pass"
  inventory:
    group_vars:
      matrix_servers:
        ansible_connection: community.docker.docker
        domain_name: "matrix.test"
        admin_username: "admin"
        admin_email: "admin@test.com"
        matrix_db_name: "synapse"
        matrix_db_user: "synapse_user"
        matrix_db_password: "test_db_password"
        matrix_port: 8008
        nginx_port: 80
verifier:
  name: testinfra
scenario:
  name: default