dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: matrix-test
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    groups:
      - matrix_servers
provisioner:
  name: ansible
  inventory:
    group_vars:
      matrix_servers:
        ansible_user: root
        domain_name: "matrix.test"
        admin_username: "admin"
        matrix_db_name: "synapse"
        matrix_db_user: "synapse_user"
        matrix_db_password: "test_db_password"
        admin_email: "admin@test.com"
verifier:
  name: testinfra
scenario:
  name: default