---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Import all test files
      include_tasks: "{{ item }}"
      with_fileglob:
        - "../default/tests/test_*.yml"
        - "../default/tests/test_*.py"
      ignore_errors: true